// lib/exports/leaveRequests.js
import {
  BRANDING,
  fetchCurrentUser,
  extractUserInfo,
  drawBizBuddyLogo,
  formatUserForFilename,
  getTimestampForFilename,
  getFormattedTimestamp,
  jsPDF,
  autoTable,
} from "./_shared.js";
import { resolveLeavePayOutcome } from "@/lib/leaveBalanceUtils";

const STATUS_LABELS = {
  pending: "Pending",
  pending_secondary: "Pending Final",
  approved: "Approved",
  rejected: "Rejected",
  cancelled: "Cancelled",
};

const PAY_LABELS = { paid: "Paid", unpaid: "Unpaid", partial: "Partially Paid" };

/**
 * Exports a company's leave requests (already filtered by the caller — e.g. by
 * the admin table's active date range/tab/search) as a branded PDF report.
 * @param {Object} params
 * @param {Array} params.data - Leave records to include (caller applies filtering)
 * @param {Object} params.user - (Optional) admin generating the report; fetched if not provided
 * @param {string} params.dateRangeLabel - Human-readable date range to print in the report header
 * @param {string} params.filename - (Optional) custom filename
 * @returns {Object} Result object with success flag and filename
 */
export const exportLeaveRequestsPDF = async ({ data, user = null, dateRangeLabel = "All dates", filename = null }) => {
  if (!data || data.length === 0) {
    throw new Error("No data to export");
  }

  try {
    const userData = user || await fetchCurrentUser();
    const doc = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();

    const userInfo = extractUserInfo(userData);
    const generatedAt = getFormattedTimestamp();
    const userForFile = formatUserForFilename(userData);
    const timestamp = getTimestampForFilename();

    // ===== HEADER SECTION =====
    let yPos = 15;
    await drawBizBuddyLogo(doc, 15, yPos);

    doc.setTextColor(...BRANDING.colors.primary);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text("LEAVE REQUESTS REPORT", pageWidth / 2, yPos + 6, { align: "center" });

    doc.setTextColor(...BRANDING.colors.dark);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.text(BRANDING.tagline, pageWidth / 2, yPos + 11, { align: "center" });

    doc.setTextColor(...BRANDING.colors.light);
    doc.setFontSize(8);
    doc.text(`Generated: ${generatedAt}`, pageWidth - 15, yPos + 3, { align: "right" });

    yPos += 18;
    doc.setDrawColor(...BRANDING.colors.primary);
    doc.setLineWidth(0.8);
    doc.line(15, yPos, pageWidth - 15, yPos);

    // ===== REPORT INFORMATION SECTION =====
    yPos += 6;
    doc.setFillColor(...BRANDING.colors.primaryLight);
    doc.roundedRect(15, yPos, pageWidth - 30, 24, 2, 2, "F");

    doc.setTextColor(...BRANDING.colors.primary);
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.text("REPORT INFORMATION", 20, yPos + 5);

    const col2X = pageWidth / 2;
    yPos += 9;
    doc.setTextColor(...BRANDING.colors.dark);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("Company:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(userInfo.companyName, 50, yPos);

    doc.setFont("helvetica", "bold");
    doc.text("Date Range:", col2X, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(dateRangeLabel, col2X + 28, yPos);

    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Generated By:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(`${userInfo.fullName} | ${userInfo.username}`, 50, yPos);

    doc.setFont("helvetica", "bold");
    doc.text("Total Records:", col2X, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(String(data.length), col2X + 28, yPos);

    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Email:", 20, yPos);
    doc.setFont("helvetica", "normal");
    doc.text(userInfo.email, 50, yPos);

    // ===== TABLE SECTION =====
    yPos += 12;
    const tableHeaders = ["Employee", "Leave Type", "Date Range", "Days", "Pay Type", "Status", "Balance", "Approver", "Decided By", "Submitted"];

    const tableData = data.map((l) => {
      const req = l.requester || l.User;
      const name = req?.name || req?.email || "Unknown";
      const s = new Date(l.startDate);
      const e = new Date(l.endDate);
      const days = Math.floor((e - s) / 86400000) + 1;
      const outcome = resolveLeavePayOutcome(l);
      return [
        name,
        l.leaveType || "—",
        `${s.toLocaleDateString()} - ${e.toLocaleDateString()}`,
        String(days),
        outcome ? PAY_LABELS[outcome] : "—",
        STATUS_LABELS[l.status] || l.status || "—",
        l.currentBalance != null ? `${Number(l.currentBalance).toFixed(2)}h` : "—",
        l.approver?.name || l.approver?.email || "—",
        l.decidedBy?.name || l.decidedBy?.email || "—",
        l.createdAt ? new Date(l.createdAt).toLocaleDateString() : "—",
      ];
    });

    autoTable(doc, {
      head: [tableHeaders],
      body: tableData,
      startY: yPos,
      margin: { left: 15, right: 15 },
      styles: {
        fontSize: 8,
        cellPadding: 2.5,
        lineColor: [200, 200, 200],
        lineWidth: 0.1,
        textColor: BRANDING.colors.dark,
      },
      headStyles: {
        fillColor: BRANDING.colors.primary,
        textColor: BRANDING.colors.white,
        fontStyle: "bold",
        halign: "center",
        fontSize: 8,
      },
      alternateRowStyles: {
        fillColor: [248, 250, 252],
      },
      columnStyles: {
        0: { cellWidth: 36, halign: "left" },
        1: { cellWidth: 28, halign: "left" },
        2: { cellWidth: 36, halign: "center" },
        3: { cellWidth: 16, halign: "center" },
        4: { cellWidth: 24, halign: "center" },
        5: { cellWidth: 24, halign: "center" },
        6: { cellWidth: 20, halign: "right" },
        7: { cellWidth: 28, halign: "left" },
        8: { cellWidth: 28, halign: "left" },
        9: { cellWidth: 24, halign: "center" },
      },
    });

    // ===== FOOTER ON ALL PAGES =====
    const pageCount = doc.internal.getNumberOfPages();
    const currentYear = new Date().getFullYear();

    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);

      doc.setDrawColor(...BRANDING.colors.light);
      doc.setLineWidth(0.3);
      doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

      doc.setTextColor(...BRANDING.colors.dark);
      doc.setFontSize(8);
      doc.setFont("helvetica", "bold");
      doc.text(`${BRANDING.companyName} | ${BRANDING.tagline}`, 15, pageHeight - 11);

      doc.setFont("helvetica", "normal");
      doc.setTextColor(...BRANDING.colors.light);
      doc.text(`© ${currentYear}`, 15, pageHeight - 7);

      doc.setTextColor(...BRANDING.colors.dark);
      doc.setFontSize(7);
      doc.text(
        `Requestor: ${userInfo.fullName} | ${userInfo.email}`,
        pageWidth / 2,
        pageHeight - 9,
        { align: "center" }
      );

      doc.setTextColor(...BRANDING.colors.light);
      doc.setFontSize(8);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, pageHeight - 9, {
        align: "right",
      });
    }

    // ===== SAVE THE PDF =====
    const finalFilename = filename || `BizBuddy_LeaveRequests_${userForFile}_${timestamp}.pdf`;
    doc.save(finalFilename);

    return { success: true, filename: finalFilename };
  } catch (error) {
    console.error("❌ Leave requests PDF export failed:", error);
    throw error;
  }
};
